.B _bettyComply
.LP
.SH NAME
_bettyComply - adjust a file to betty's standards
.br
.LP
.SH SYNOPSIS
_bettyComply [OPTION]... [FILE]...
.br
.LP

.SH DESCRIPTION
_bettyComply is a restricted C file formatter that formats a file to comply with betty's standards. betty is an alx's C code parser that checks for errors in syntactic structure. This script modifies the input file in place.
.LP
.SH OPTIONS
.TP
.B - ..
Information not available
.TP
.B - ..
Information not available
.LP

.SH AUTHOR
Hazel Daniel
.br
.SH REPORTING BUGS
Report bugs at https://github.com/HazelDaniel/betty-comply/issues.
.br
.SH CONTRIBUTING
To contribute to the project, visit https://github.com/HazelDaniel/betty-comply.
.br
.SH COPYRIGHT
Copyright (co 2023 Hazel Daniel.
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
